version: '3.8'
services:
  stats-server:
    build: ./statistic
    ports:
      - "9090:9090"
    depends_on:
      - ewm-service
      - stats-db
    environment:
      - SPRING_DATASOURCE_STAT_URL=jdbc:postgresql://stats-db:5432/postgres
      - STAT_POSTGRES_USER=root
      - STAT_POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - STAT_SERVER_NAME=stats-server
      - STAT_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_SERVER_URL=jdbc:postgresql://ewm-db:5432/postgres
      - SERVER_POSTGRES_USER=root
      - SERVER_POSTGRES_PASSWORD=root

  ewm-db:
    image: postgis/postgis
    ports:
      - "6543:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'su postgres', '&&', 'pg_isready' ]
      interval: 20s
      timeout: 20s
      retries: 10
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root